- name: Create project directory
  file: path={{ default_deployment_dir }}{{ project_name }} state=directory mode=0755

- name: Create artifact directory
  file: path={{ default_deployment_dir }}{{ project_name }}/{{ artifact_id }} state=directory mode=0755

- name: deploying artifact {{ artifact_id }} of project {{ project_name }}
  copy: src={{ artifact_path }}
       dest={{ default_deployment_dir }}{{ project_name }}/{{ artifact_id }}

- name: Create link
  file: path={{ default_deployment_dir }}{{ project_name }}/current src=/var/www/{{ project_name }}/{{ artifact_id }} state=link mode=0755
  notify:
      - restart apache2
