- name: Create project directory
  file: path=/var/www/bewamo-ui state=directory mode=0755

- name: Create project directory
  file: path=/var/www/bewamo-ui/bewamo state=directory mode=0755

- name: cloning repo
  copy: src=/var/lib/jenkins/workspace/Bewamo-ui_BuildAndDeployToStaging/dist/
       dest=/var/www/bewamo-ui/bewamo

- name: Create link
  file: path=/var/www/bewamo-ui/current src=/var/www/bewamo-ui/bewamo state=link mode=0755
  notify:
      - restart apache2
