- name: Create directory
  file: path=/var/www/bewamo-ui state=directory mode=0755

- name: unarchiving
  unarchive: src=/home/ubuntu/bewamo.tgz dest=/var/www/bewamo-ui/

- name: Create link
  file: path=/var/www/current src=/var/www/bewamo-ui/bewamo state=link mode=0755
  notify:
      - restart apache2