- name: Create directory
  file: path=/var/www/bewamo-ui state=directory mode=0755

- name: Deploying bewamo.tgz to staging
  copy: src=/home/ubuntu/bewamo.tgz dest=/var/www/bewamo-ui/bewamo.tgz owner=www-data group=www-data mode=0644

- name: unarchiving
  unarchive: src=/var/www/bewamo-ui/bewamo.tgz dest=/var/www/bewamo-ui/bewamo

- name: Create link
  file: path=/var/www/current src=/var/www/bewamo-ui/bewamo state=link mode=0755
  notify:
      - restart apache2