- name: Create project directory
  file: path=/var/www/{{ project_name }} state=directory mode=0755

- name: Create project directory
  file: path=/var/www/{{ project_name }}/bewamo state=directory mode=0755

- name: cloning repo
  copy: src=/var/lib/jenkins/workspace/Bewamo-ui_BuildAndDeployToStaging/dist/
       dest=/var/www/{{ project_name }}/bewamo

- name: Create link
  file: path=/var/www/{{ project_name }}/current src=/var/www/{{ project_name }}/bewamo state=link mode=0755
  notify:
      - restart apache2
