---
- name: Deploy Bewamo-ui
  hosts: tag_Name_{{ tag_name }}
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    project_name: bewamo-ui
    artifact_path: '/var/lib/jenkins/workspace/Bewamo-ui_BuildAndDeployToStaging/dist/'
    artifact_id: bewamo

  roles:
    - common
    - {role: apache2, project_name: {{ project_name }}}
    - {role: deploy, project_name: {{ project_name }},
              artifact_path: {{ artifact_path }},
              artifact_id: 'bewamo'}
